
/* Список приоритетных тэгов */
export const TAGS_LIST: Record<string, string> = {
    '/tags/419/games': 'Игры',
    '/tags/105/movies': 'Кино',
    '/tags/3162/tv-series': 'Сериалы',
    '/tags/590/anime': 'Аниме',
    '/tags/3/pc': 'PC',
    '/tags/396/ps4': 'PS4',
    '/tags/3302/ps5': 'PS5',
    '/tags/2975/xbox-one': 'Xbox One',
    '/tags/13413/xbox-series-x': 'Xbox Series X',
    '/tags/7576/nintendo-switch': 'Nintendo Switch',
    '/tags/2656/vr': 'VR',
    '/tags/157/guide': 'Гайды',
    '/tags/3738/arts': 'Дизайн и Арт',
    '/tags/6/gadgets': 'Гаджеты',
    '/tags/3507/hardware': 'Железо',
    '/tags/710/science': 'Наука',
    '/tags/1622/technology': 'IT и Технологии',
    '/tags/796/iOS': 'iOS',
    '/tags/860/android': 'Android',
    '/tags/217/review': 'Обзоры',
    '/tags/3261/opinion': 'Мнения',
    '/tags/2473/feature': 'Фичеры',
    '/tags/8/other': 'Другое',
    '/tags/8/drugoe': 'Другое',
};